# Generated by Django 4.1 on 2022-10-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password2',
        ),
    ]
